INSERT INTO `settings` VALUES(NULL, 1, 'bookmarks', 'widgets', 'TRUE');
INSERT INTO `settings` VALUES(NULL, 1, 'bookmarks', 'categories', 'TRUE');
INSERT INTO `settings` VALUES(NULL, 1, 'bookmarks', 'enabled', 'TRUE');
INSERT INTO `settings` VALUES(NULL, 1, 'bookmarks', 'date_style', 'DIGITS');
INSERT INTO `settings` VALUES(NULL, 1, 'bookmarks', 'categories_display', 'yes');
INSERT INTO `settings` VALUES(NULL, 1, 'bookmarks', 'shorten_url', 'yes');
INSERT INTO `settings` VALUES(NULL, 1, 'bookmarks', 'url_shortener', 'bitly');
INSERT INTO `settings` VALUES(NULL, 1, 'bookmarks', 'comments_per_page', '5');
INSERT INTO `settings` VALUES(NULL, 1, 'bookmarks', 'comments_allow', 'no');